# Generated by Django 2.2 on 2021-03-17 11:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useroperation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30, unique=True, verbose_name='类别名')),
            ],
            options={
                'verbose_name_plural': '类别',
                'db_table': 'blog_category',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=20, unique=True, verbose_name='标签名')),
            ],
            options={
                'verbose_name_plural': '标签',
                'db_table': 'blog_tag',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='imgs')),
                ('about', models.CharField(max_length=100)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Category')),
                ('tag', models.ManyToManyField(to='post.Tag')),
            ],
            options={
                'verbose_name_plural': '帖子',
                'db_table': 'blog_post',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='post.Post', verbose_name='点赞')),
                ('u_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useroperation.User')),
            ],
            options={
                'verbose_name_plural': '点赞',
                'db_table': 'post_like',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.Post', verbose_name='评论')),
                ('u_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useroperation.User')),
            ],
            options={
                'verbose_name_plural': '评论',
                'db_table': 'post_comment',
            },
        ),
    ]
