# Generated by Django 2.2 on 2021-03-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.BooleanField(default=False),
        ),
    ]
