# Generated by Django 2.2 on 2021-03-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210318_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='good',
            field=models.BooleanField(default=False),
        ),
    ]
