# Generated by Django 2.2 on 2021-03-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
